### ISSUE TITLE
remove unnecessary models context manager override

### ISSUE THREAD

**Issue by mosihere** [AisDisappeared/todo#4]
1- you should not explicitly override context manager
each Model has 'objects' as its default context manager
we must only override objects attribute
when we extend the objects functionality for specific model

2- it is better to not use __all__ for fields to serialize in serializer module
sometimes we add some fields and we want to protect them and not expose all fields
that approach you used, can cause unwanted potential security risk in future

**Comment by AisDisappeared** [comment]
Hey, it’s right bro.
I checked and merged your pr.👌🏿
